version: '3.3'

services:
  civil:
    build: ./
    image: ji:0.1
    container_name: ji
    restart: always
    environment:
      MYSQL_DSN: "root:root@tcp/ji_db?charset=utf8&parseTime=True&loc=Local"
    ports:
      - 4000:4000
    depends_on:
      - mysql
      - redis

  mysql:
    container_name: ji_mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: ji_db
    volumes:
      - /var/lib/mysql/ji_mysql:/var/lib/mysql
    ports:
      - 3306:3306
  
  redis:
    container_name: ji_redis
    image: redis:6.0
    restart: always
    volumes:
      - /usr/local/redis:/usr/local/redis
    ports:
      - 6379:6379
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.0
    container_name: ji_es
    environment:
      - "ES_JAVA_OPTS=-Xms64m -Xmx251m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /usr/local/elasticsearch/data:/usr/local/elasticsearch/data
      - /usr/local/elasticsearch/config/es/config:/usr/local/elasticsearch/config
    ports:
      - 9200:9200
    restart: always

  rabbitmq:
    image: rabbitmq:3.8.3-management
    container_name: ji_rabbitmq
    restart: always
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - /var/log/rabbitmq:/var/log/rabbitmq 
      - /var/lib/rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=123456
  
  kibana:
    image: docker.elastic.co/kibana/kibana:7.1.0
    container_name: ji_kibana
    environment:
      - I18N_LOCALE=zh-CN
      - XPACK_GRAPH_ENABLED=true
      - TIMELION_ENABLED=true
      - XPACK_MONITORING_COLLECTION_ENABLED="true"
    ports:
      - 5601:5601
    restart: always